name: Metrics

on:
  schedule:
    - cron: "10 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate metrics (to output branch)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic

          # IMPORTANT: publish directly to output branch
          output_action: github-pages
          committer_branch: output
          filename: assets/metrics.svg

          config_timezone: America/Sao_Paulo
          base: header, activity, repositories

          # Clean + terminal vibe
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes

          # (Opcional) esse aqui Ã© o que mais consome Search API.
          # Se ainda der rate limit, desligue:
          plugin_notable: no
