with:
  token: ${{ secrets.METRICS_TOKEN }}
  user: arturseccode
  template: classic

  # Base leve (r√°pido)
  base: header, community

  config_timezone: America/Sao_Paulo
  config_display: large
  config_output: svg

  filename: assets/metrics.svg
  committer_branch: output
  committer_message: "chore: update metrics"

  # Evita ficar esperando e estourar tempo
  retries: 0

  # Reduz carga de API
  repositories: 30
  repositories_batch: 30

  # Linguagens bem leve
  plugin_languages: yes
  plugin_languages_indepth: no
  plugin_languages_limit: 6
  plugin_languages_analysis_timeout: 5
  plugin_languages_sections: most-used
  plugin_languages_details: bytes-size,percentage

  # Desabilitados
  plugin_habits: no
  plugin_achievements: no
  plugin_notable: no
  plugin_stars: no
  plugin_topics: no
